import crypto from 'node:crypto'

/**
 * Mercado Pago webhook signature validation.
 *
 * MP sends two headers on every notification:
 *   x-signature:  ts=1704908010,v1=<hmac-sha256-hex>
 *   x-request-id: <uuid>
 *
 * The signed manifest is exactly:  id:<data.id>;request-id:<x-request-id>;ts:<ts>;
 * and the key is the "Clave secreta" shown in MP → Tus aplicaciones → Webhooks.
 * (It is NOT an arbitrary string we choose — it is generated by Mercado Pago.)
 *
 * Docs: https://www.mercadopago.com.ar/developers/es/docs/your-integrations/notifications/webhooks
 */

export const MP_WEBHOOK_SECRET = process.env.MP_WEBHOOK_SECRET?.trim() || ''

export type SignatureResult = { ok: true } | { ok: false; reason: string }

function parseSignatureHeader(header: string): { ts?: string; v1?: string } {
  const out: { ts?: string; v1?: string } = {}
  for (const part of header.split(',')) {
    const [rawKey, ...rest] = part.split('=')
    const key = rawKey?.trim()
    const value = rest.join('=').trim()
    if (key === 'ts') out.ts = value
    else if (key === 'v1') out.v1 = value
  }
  return out
}

function safeEqualHex(a: string, b: string): boolean {
  const bufA = Buffer.from(a, 'hex')
  const bufB = Buffer.from(b, 'hex')
  if (bufA.length === 0 || bufA.length !== bufB.length) return false
  return crypto.timingSafeEqual(bufA, bufB)
}

/**
 * Verifies the x-signature header against the secret.
 * Returns ok:false with a reason when the request cannot be trusted.
 */
export function verifyMpSignature(req: Request, dataId: string): SignatureResult {
  if (!MP_WEBHOOK_SECRET) return { ok: false, reason: 'no-secret-configured' }

  const signature = req.headers.get('x-signature')
  if (!signature) return { ok: false, reason: 'missing-x-signature' }

  const { ts, v1 } = parseSignatureHeader(signature)
  if (!ts || !v1) return { ok: false, reason: 'malformed-x-signature' }

  const requestId = req.headers.get('x-request-id') ?? ''
  // MP lowercases alphanumeric ids when building the manifest.
  const id = /^[a-zA-Z0-9]+$/.test(dataId) ? dataId.toLowerCase() : dataId
  const manifest = `id:${id};request-id:${requestId};ts:${ts};`

  const expected = crypto.createHmac('sha256', MP_WEBHOOK_SECRET).update(manifest).digest('hex')
  if (!safeEqualHex(expected, v1)) return { ok: false, reason: 'signature-mismatch' }

  // Reject stale notifications (replay window: 10 minutes).
  const tsMs = Number(ts) * (String(ts).length > 12 ? 1 : 1000)
  if (Number.isFinite(tsMs) && Math.abs(Date.now() - tsMs) > 10 * 60 * 1000) {
    return { ok: false, reason: 'timestamp-out-of-window' }
  }

  return { ok: true }
}
